version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: simplecov
    versions:
    - "> 0.17.1"
  - dependency-name: simplecov
    versions:
    - ">= 0.18.a, < 0.19"
  - dependency-name: view_component
    versions:
    - 2.31.0
  - dependency-name: govuk-components
    versions:
    - 1.1.4
    - 1.1.5
    - 1.1.7
    - 1.1.8
  - dependency-name: bootsnap
    versions:
    - 1.6.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - DevOps
  - dependencies
  - github_actions
- package-ecosystem: terraform
  directory: "/terraform"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - DevOps
  - dependencies
  - terraform
