inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml # add this line for Rails projects

AllCops:
  Exclude:
    - "bin/rails"
    - "bin/rake"
    - "bin/setup"
    - "bin/update"
    - "bin/yarn"
    - "bin/webpack"
    - "bin/webpack-dev-server"
    - "node_modules/**/*"

Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Rails/HelperInstanceVariable:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true


# rubocop-govuk 3.17.0 started to enforce this but no active record is actually in use
# https://github.com/alphagov/rubocop-govuk/commit/c4a4329d5e44dc98b24f1d344a3532054b1539e0
Rails/SaveBang:
  Enabled: false
