default: &default
  ASSETS_PRECOMPILE: true
  RAILS_SERVE_STATIC_FILES: true
  WEBPACKER_DEV_SERVER_HOST: "webpacker"

qa:
  <<: *default
  RAILS_ENV: qa
  RACK_ENV: qa

staging:
  <<: *default
  RAILS_ENV: staging
  RACK_ENV: staging

prod:
  <<: *default
  RAILS_ENV: production
  RACK_ENV: production

sandbox:
  <<: *default
  RAILS_ENV: sandbox
  RACK_ENV: sandbox

review:
  <<: *default
  RAILS_ENV: review
  RACK_ENV: review
