#
# DO NOT EDIT THIS FILE. It was copied from Apply by the rubocop:copy_config_from_apply task at 2021-06-20 22:18:41 UTC
# Add overrides in this repository’s .rubocop.yml
#


module RuboCop
  module Cop
    module Govuk
      class GovukLinkTo < Base
        def on_send(node)
          return unless node.method_name == :link_to

          add_offense(node, message: 'Use govuk_link_to or govuk_back_link_to instead of link_to')
        end
      end
    end
  end
end
