#
# DO NOT EDIT THIS FILE. It was copied from Apply by the rubocop:copy_config_from_apply task at 2022-07-08 08:16:56 UTC
# Add overrides in this repository’s .rubocop.yml
#

module RuboCop
  module Cop
    module Govuk
      class GovukButtonTo < Base
        def on_send(node)
          return unless node.method_name == :button_to

          add_offense(node, message: 'Use govuk_button_to instead of button_to')
        end
      end
    end
  end
end
