{
 "title": "FIND-QA",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    { "expr": "rate(requests[1m])" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "find-qa - memory utilization",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(memory_bytes{app=\"find-qa\"})"
    },
    {
     "expr": "min(memory_bytes{app=\"find-qa\"})"
    },
    {
     "expr": "max(memory_bytes{app=\"find-qa\"})"
    }
   ]
  },
  {
   "title": "CPU (find-qa)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(cpu{app=\"find-qa\"}) "
    },
    {
     "expr": "min(cpu{app=\"find-qa\"}) "
    },
    {
     "expr": "max(cpu{app=\"find-qa\"}) "
    }
   ]
  }
 ]
}