manage_backend:
  # URL of the API app (manage-courses-backend)
  base_url: http://localhost:3001
current_cycle: 2020
google:
  maps_api_key: replace_me
service_support:
  contact_email_address: becomingateacher@digital.education.gov.uk
