manage_backend:
  # URL of the API app (manage-courses-backend)
  base_url: http://localhost:3001
current_cycle: 2020
google:
  maps_api_key: replace_me
  maps_api_url: https://maps.googleapis.com/maps/api/staticmap
service_support:
  contact_email_address: becomingateacher@digital.education.gov.uk
redirect_results_to_c_sharp: true
gcp_api_key: please_change_me
