teacher_training_api:
  base_url: http://localhost:3001
valid_referers:
  - http://localhost:5000
log_level: debug
redis_url: redis://localhost:6379/0
background_jobs: # scheduled jobs run on all environments except dev and test
feature_flags:
  cache_courses: true
