teacher_training_api:
  base_url: http://localhost:3001
valid_referers:
  - http://localhost:5000
log_level: debug
redis_url: redis://localhost:6379/0
feature_flags:
  cache_courses: true
  cache_providers: true
