base_url: https://find-loadtest.london.cloudapps.digital
apply_base_url: https://apply-load-test.london.cloudapps.digital
teacher_training_api:
  base_url: https://teacher-training-api-loadtest.london.cloudapps.digital
valid_referers:
  - https://find-loadtest.london.cloudapps.digital

feature_flags:
  send_web_requests_to_big_query: false
