base_url: https://www.find-postgraduate-teacher-training.service.gov.uk
assets_url: https://assets.find-postgraduate-teacher-training.service.gov.uk
apply_base_url: https://www.apply-for-teacher-training.service.gov.uk
teacher_training_api:
  base_url: https://api.publish-teacher-training-courses.service.gov.uk
valid_referers:
  - https://www.find-postgraduate-teacher-training.education.gov.uk

feature_flags:
  send_web_requests_to_big_query: true
  cache_courses: true
  provider_autocomplete: false
  bursaries_and_scholarships_announced: true
