base_url: https://qa.find-postgraduate-teacher-training.service.gov.uk
apply_base_url: https://qa.apply-for-teacher-training.service.gov.uk
teacher_training_api:
  base_url: https://api.publish-teacher-training-courses.service.gov.uk
valid_referers:
  - https://qa.find-postgraduate-teacher-training.education.gov.uk

feature_flags:
  send_web_requests_to_big_query: true
  degree_required_filter: true
