base_url: https://www.qa.find-postgraduate-teacher-training.service.gov.uk
teacher_training_api:
  base_url: https://api2.qa.publish-teacher-training-courses.service.gov.uk
search_and_compare_ui:
  base_url: https://www.qa.find-postgraduate-teacher-training.service.gov.uk
valid_referers:
  - https://www.qa.find-postgraduate-teacher-training.education.gov.uk
