apply_base_url: https://qa.apply-for-teacher-training.service.gov.uk
teacher_training_api:
  base_url: https://qa.api.publish-teacher-training-courses.service.gov.uk
basic_auth_username: find
basic_auth_password: bat
