apply_base_url: https://qa.apply-for-teacher-training.service.gov.uk
teacher_training_api:
  base_url: https://qa.api.publish-teacher-training-courses.service.gov.uk
feature_flags:
  new_filters: true
