base_url: https://find-rollover.london.cloudapps.digital
#assets_url: https://rollover-assets.find-postgraduate-teacher-training.service.gov.uk
apply_base_url: https://apply-rollover.london.cloudapps.digital
teacher_training_api:
  base_url: https://teacher-training-api-rollover.london.cloudapps.digital
valid_referers:
  - https://find-rollover.london.cloudapps.digital
