base_url: https://sandbox.find-postgraduate-teacher-training.service.gov.uk
apply_base_url: https://sandbox.apply-for-teacher-training.service.gov.uk
teacher_training_api:
  base_url: https://sandbox.api.publish-teacher-training-courses.service.gov.uk
valid_referers:
  - https://sandbox.find-postgraduate-teacher-training.education.gov.uk
