base_url: https://staging.find-postgraduate-teacher-training.service.gov.uk
apply_base_url: https://staging.apply-for-teacher-training.service.gov.uk
teacher_training_api:
  base_url: https://staging.api.publish-teacher-training-courses.service.gov.uk
valid_referers:
  - https://staging.find-postgraduate-teacher-training.education.gov.uk

feature_flags:
  send_web_requests_to_big_query: true
