base_url: https://staging.find-postgraduate-teacher-training.service.gov.uk
teacher_training_api:
  base_url: https://teacher-training-api-prod.london.cloudapps.digital
valid_referers:
  - https://staging.find-postgraduate-teacher-training.education.gov.uk
