manage_backend:
  base_url: https://api2.staging.publish-teacher-training-courses.service.gov.uk
search_and_compare_ui:
  base_url: https://www.staging.find-postgraduate-teacher-training.service.gov.uk
find_teacher_training:
  base_url: https://www2.staging.find-postgraduate-teacher-training.service.gov.uk
