teacher_training_api:
  base_url: http://localhost:3001
valid_referers:
  - http://localhost:9000
feature_flags:
  new_filters: false
  ucas_only_locations: false
google:
  bigquery_project_id: bat-find-test
  bigquery_dataset: bat-find-test-events
