teacher_training_api:
  base_url: http://localhost:3001
valid_referers:
  - http://localhost:9000
google:
  big_query:
    project_id: bat-find-test
    dataset: bat-find-test-events
redis_url: redis://localhost:6379/9
feature_flags:
  new_filters: true
  cache_courses: true
