teacher_training_api:
  base_url: http://localhost:3001
valid_referers:
  - http://localhost:9000
google:
  big_query:
    project_id: bat-find-test
    dataset: bat-find-test-events
redis_url: redis://localhost:6379/9
background_jobs: # scheduled jobs run on all environments except dev and test - see settings:
basic_auth_enabled: false
basic_auth_username: foo
basic_auth_password: bar
