name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DOCKERHUB_REPOSITORY: dfedigital/find-teacher-training

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/turnstyle@v1
        name: Wait for other runs
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_API_ACCESS_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DOCKERHUB_REPOSITORY }}
          tags: ${{ github.sha }}
          build_args: COMMIT_SHA=${{ github.sha }}

      - name: Set Environment variable
        run: |
          echo "DOCKER_IMAGE=$DOCKER_IMAGE" >> $GITHUB_ENV
        env:
          DOCKER_IMAGE: ${{ format('{0}:{1}', env.DOCKERHUB_REPOSITORY, github.sha) }}

      - name: Run ruby linter
        run: make rubocop
      
      - name: Run sass linter
        run: make lint-sass
      
      - name: Run brakeman static analysis
        run: make brakeman
      
      - name: Run ruby tests
        run: make rspec
      
      - name: Run javascript tests
        run: make js.test

      - name: Publish Test Coverage to Code Climate
        run: |
          make publish.codeclimate
        env:
          GIT_BRANCH: ${{ github.ref }}
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}
      
      - name: Trigger QA Deployment
        if: ${{ success() && github.ref == 'refs/heads/master' }}
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: Deploy
          token: ${{ secrets.ACTIONS_API_ACCESS_TOKEN }}
          inputs: '{"environment": "qa", "sha": "${{ github.sha }}"}'
