name: Deploy
concurrency: build_and_deploy_${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        type: choice
        required: true
        options:
        - qa
        - staging
        - production
        - sandbox
        - rollover
        - loadtest
      sha:
        description: Commit sha to be deployed
        required: true

jobs:
  deploy:
    name: ${{ github.event.inputs.environment }} deployment
    environment:
      name: ${{ github.event.inputs.environment }}
      url: ${{ steps.deploy_app.outputs.deploy-url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy App to ${{ github.event.inputs.environment }} environment
        id: deploy_app
        uses: ./.github/actions/deploy/
        with:
          azure_credentials: ${{ secrets[format('AZURE_CREDENTIALS_{0}', github.event.inputs.environment)] }}
          environment: ${{ github.event.inputs.environment }}
          sha: ${{ github.event.inputs.sha }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          terraform-state-access-key: ${{ secrets[format('TERRAFORM_STATE_ACCESS_KEY_{0}', github.event.inputs.environment)] }}
