name: Smoke Tests
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to run tests against.
        required: true

jobs:
  smoke_tests:
    name: Run Smoke Tests on ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment variable
        run: |
          echo "RAILS_ENV=$RAILS_ENV" >> $GITHUB_ENV
          echo "CYPRESS_ENVIRONMENT=$RAILS_ENV" >> $GITHUB_ENV
        env:
          RAILS_ENV: ${{ github.event.inputs.environment }}

      - name: Cypress Run against ${{ github.event.inputs.environment }}
        run: | 
          npm install
          npx cypress run
