name: Smoke Tests
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to run tests against (qa, staging, production or sandbox)'
        required: true

jobs:
  smoke_tests:
    name: smoke-tests-${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/turnstyle@v1
        name: Wait for other runs
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_API_ACCESS_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          repository: DFE-Digital/find-teacher-training-tests
          ref: refs/heads/master
          token: ${{ secrets.ACTIONS_API_ACCESS_TOKEN }}

      - name: Set Environment variable
        run: |
          echo "RAILS_ENV=$RAILS_ENV" >> $GITHUB_ENV
          echo "CYPRESS_ENVIRONMENT=$RAILS_ENV" >> $GITHUB_ENV
        env:
          RAILS_ENV: ${{ github.event.inputs.environment }}

      - name: Cypress Run against ${{ github.event.inputs.environment }}
        id: cypress_run
        run: |
          npm install
          npx cypress run

      - name: 'Nofiy #twd_apply_tech on failure'
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: twd_apply_tech
          SLACK_COLOR: '#ef5343'
          SLACK_ICON_EMOJI: ':sad-beaver:'
          SLACK_USERNAME: Find Teacher Training
          SLACK_TITLE: Smoke tests failure
          SLACK_MESSAGE: ':alert: Smoke tests failure on ${{ github.event.inputs.environment }} :sadparrot:'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
